config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'friends#index'
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
   validates :first_name , presence: true
   validates :last_name , presence: true
   validates :phone , presence: true
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
  validates :email , :email => {:strict_mode => true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /friends or /friends.json
  def index
    if !user_signed_in?
      redirect_to new_user_session_path
    else
      @friends = current_user.friends
    end
  end

  # GET /friends/1 or /friends/1.json
  def show
    if @friend.user != current_user
      redirect_to root_path
    end
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
    if @friend.user != current_user
      redirect_to root_path
    end
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)
    @friend.user = current_user
    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    if @friend.user != current_user
      redirect_to root_path
    else
      respond_to do |format|
        if @friend.update(friend_params)
          format.html { redirect_to @friend, notice: "Friend was successfully updated." }
          format.json { render :show, status: :ok, location: @friend }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @friend.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    if @friend.user != current_user
      redirect_to root_path
    end
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label "First Name *" ,class: 'form-label' %>
    <%= form.text_field :first_name,class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= form.label "Last Name *", class: 'form-label' %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= form.label :email, class: 'form-label' %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= form.label "Phone No *",class: 'form-label' %>
    <%= form.text_field :phone,class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= form.label :twitter,class: 'form-label' %>
    <%= form.text_field :twitter,class: 'form-control' %>
  </div>

  <div class='hvr-sweep-to-right border' > 
    <%= form.submit class: 'btn'  %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend, class: 'btn mt-1 hvr-sweep-to-right border bg-light' %> |
<%= link_to 'Back', friends_path, class: 'btn mt-1 hvr-sweep-to-right border bg-light' %>

app/views/friends/index.html.erb
<h1>Friends</h1>

<table class='table table-striped' >
  <thead >
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= link_to 'Show', friend,class: 'btn btn-sm hvr-sweep-to-right text-primary' %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) ,class: 'btn btn-sm text-warning hvr-sweep-to-right'%></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn text-danger btn-sm hvr-sweep-to-right'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class: 'btn hvr-sweep-to-right border' %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path , class: 'btn hvr-sweep-to-left border mt-1' %>

app/views/friends/show.html.erb
<p>
  <strong>First name: </strong>
  <%= @friend.first_name.capitalize %>
</p>

<p>
  <strong>Last name: </strong>
  <%= @friend.last_name.capitalize %>
</p>

<p>
  <strong>Email: </strong>
  <%= @friend.email %>
</p>

<p>
  <strong>Phone: </strong>
  <%= @friend.phone %>
</p>

<p>
  <strong>Twitter: </strong>
  <%= @friend.twitter %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) ,class: 'btn hvr-sweep-to-right border' %> |
<%= link_to 'Back', friends_path ,class: 'btn hvr-sweep-to-right border'%>

app/views/home/index.html.erb
<h1>Hello World</h1>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friends', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        

        <% if user_signed_in? %>
        
            <li class="nav-item">
                <%= link_to  'Create New Friend' , new_friend_path , class: 'nav-link' %>
            </li>

            <li class="nav-item">
            <%= link_to  'Sing Out' , destroy_user_session_path , method: :delete , class: 'nav-link' %>
            </li>

            <li class="nav-item">
            <%= link_to  'Edit Profile' , edit_user_registration_path , class: 'nav-link' %>
            </li>

        <% else %>

            <li class="nav-item">
            <%= link_to  'Sign Up' , new_user_registration_path , class: 'nav-link' %>
            </li>

            <li class="nav-item">
            <%= link_to  'Log In' , new_user_session_path , class: 'nav-link' %>
            </li>

        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Friends</title>
  </head>
  <body>
  <%= render "layouts/header" %>
    <div class='container'> 
    <br/>
    <% flash.each do |name, msg| %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <br/>
        <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>